server:
  port: 8080
spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/galaxy?useSSL=false
    username: root
    password: ''
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_absent
  application:
    name: a-bootiful-scala-client
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true

      discovery:
        enabled: true
        port: ${server.port}
        register: true
        deregister: false
        prefer-ip-address: true
        health-check-interval: 15s
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        catalog-services-watch-delay: 10
        prefer-agent-address: true
      config:
        enabled: true
        format: key_value
        watch:
          enabled: true
          delay: 1000
          wait-time: 60
        fail-fast: false
        prefix: config
        name: ${spring.application.name}

  # Customizing the Banner：YAML treats 'off' value as boolean type, whereas Spring tries to convert it to the enum type Banner.Mode.
  main:
    banner-mode: 'OFF'

logging:
  config: classpath:log4j2.properties

management:
  endpoints:
    web:
      exposure:
        include: '*'